@startuml
left to right direction
skinparam packageStyle rectangle

actor "Pasien" as P
actor "Petugas Pendaftaran" as PP
actor "Dokter" as D
actor "Apoteker" as A
actor "Kepala Puskesmas" as KP
actor "Admin Sistem" as AS

package "Sistem Informasi Puskesmas" {
    ' --- PASIEN ---
    usecase "Melakukan pendaftaran kunjungan" as UC_Pasien

    ' --- PETUGAS PENDAFTARAN ---
    usecase "Registrasi pasien baru" as UC_RegBaru
    usecase "Verifikasi data pasien lama" as UC_VerifLama
    usecase "Daftar kunjungan ke poli" as UC_DaftarPoli
    usecase "Mencatat status pembayaran (Umum)" as UC_BayarUmum
    usecase "Mencatat data/klaim BPJS" as UC_BPJS

    ' --- DOKTER ---
    usecase "Melihat data pasien" as UC_LihatData
    usecase "Mengisi rekam medis" as UC_RekamMedis
    usecase "Mencatat tanda vital" as UC_TTV
    usecase "Membuat resep obat" as UC_Resep

    ' --- APOTEKER ---
    usecase "Menerima resep dari sistem" as UC_TerimaResep
    usecase "Mengecek ketersediaan stok" as UC_CekStok
    usecase "Menyerahkan obat ke pasien" as UC_SerahObat
    usecase "Menandai resep 'obat tidak lengkap'" as UC_ObatKurang
    usecase "Mencatat pengeluaran obat" as UC_CatatKeluar

    ' --- KEPALA PUSKESMAS ---
    usecase "Menghasilkan laporan" as UC_GenReport
    usecase "Melihat laporan kunjungan" as UC_LapKunjungan
    usecase "Melihat laporan penyakit" as UC_LapPenyakit
    usecase "Melihat laporan obat" as UC_LapObat

    ' --- ADMIN ---
    usecase "Mengelola data pengguna" as UC_User
    usecase "Mengelola master data" as UC_Master
}

' Relasi Pasien
P --> UC_Pasien

' Relasi Petugas (Sesuai Petunjuk Relasi Hal 1)
PP --> UC_RegBaru
PP --> UC_VerifLama
PP --> UC_BayarUmum
PP --> UC_BPJS

' Aturan Include dari PDF 
UC_RegBaru ..> UC_DaftarPoli : <<include>>
UC_VerifLama ..> UC_DaftarPoli : <<include>>

' Relasi Dokter
D --> UC_RekamMedis
D --> UC_Resep
' Aturan Include dari PDF [cite: 48]
UC_RekamMedis ..> UC_LihatData : <<include>>
' (PDF bilang Tanda Vital digabung dlm pemeriksaan/rekam medis [cite: 31])
UC_RekamMedis ..> UC_TTV : <<include>>

' Relasi Apoteker
A --> UC_SerahObat
A --> UC_ObatKurang
A --> UC_CatatKeluar
' Aturan Include dari PDF [cite: 49]
UC_SerahObat ..> UC_TerimaResep : <<include>>
UC_SerahObat ..> UC_CekStok : <<include>>

' Relasi Kepala Puskesmas (Generalisasi [cite: 50])
KP --> UC_GenReport
UC_LapKunjungan --|> UC_GenReport
UC_LapPenyakit --|> UC_GenReport
UC_LapObat --|> UC_GenReport

' Relasi Admin
AS --> UC_User
AS --> UC_Master

@enduml